version: '3.8'

services:
  db:
    image: postgres:15
    container_name: globetrotter_db
    restart: always
    environment:
      POSTGRES_USER: Krishanu1137
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: globetrotter
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - globenet

  backend:
    build: .
    container_name: globetrotter_backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_USER: Krishanu1137
      DB_PASSWORD: mysecretpassword
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: globetrotter
      JWT_SECRET: 9280a64c61e31480f7f741bad4f4f31a00a6f1798b758d56a13c1e9a6b5c2cea
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    networks:
      - globenet

volumes:
  pgdata:

networks:
  globenet:
