-- USERS TABLE
CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(100) NOT NULL UNIQUE,
  email VARCHAR(150) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- SCORES TABLE
CREATE TABLE IF NOT EXISTS scores (
  id SERIAL PRIMARY KEY,
  user_id INTEGER UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  total_score INTEGER DEFAULT 0,
  correct_answers INTEGER DEFAULT 0,
  incorrect_answers INTEGER DEFAULT 0,
  total_attempts INTEGER DEFAULT 0
);

-- DESTINATIONS TABLE
CREATE TABLE IF NOT EXISTS destinations (
  id SERIAL PRIMARY KEY,
  city VARCHAR(100) NOT NULL,
  country VARCHAR(100) NOT NULL,
  clues TEXT[],       -- Array of clues
  fun_fact TEXT[],    -- Array of fun facts
  trivia TEXT[]       -- Array of trivia
);

-- CITY TABLE
CREATE TABLE IF NOT EXISTS city (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL
);


-- DESTINATIONS SEED DATA
INSERT INTO destinations (city, country, clues, fun_fact, trivia) VALUES
  ('Paris', 'France',
    ARRAY['Home to the Eiffel Tower', 'Known as the City of Love'],
    ARRAY['The Eiffel Tower was initially intended to be dismantled', 'Paris has only one stop sign in the entire city'],
    ARRAY['Famous for croissants and macarons', 'Originally a Roman city called Lutetia']),
  ('Tokyo', 'Japan',
    ARRAY['Busiest pedestrian crossing in the world', 'District dedicated to anime and manga'],
    ARRAY['Originally a small fishing village called Edo', 'More than 14 million people live in Tokyo'],
    ARRAY['Over 160,000 restaurants', 'Subway system is so efficient that train delays of just a few minutes come with formal apologies']),
  ('New York', 'USA',
    ARRAY['Home to the Statue of Liberty', 'Known for Broadway theaters'],
    ARRAY['Statue of Liberty was originally a copper color before oxidizing to its iconic green patina', 'Times Square was once called Longacre Square'],
    ARRAY['468 subway stations', 'Empire State Building has its own zip code: 10118']),
  ('Berlin', 'Germany',
    ARRAY['Known for the Berlin Wall', 'Rich in history and culture'],
    ARRAY['Berlin Wall fell in 1989', 'Home to the Brandenburg Gate'],
    ARRAY['Famous for its beer gardens', 'Hosts the annual Oktoberfest']),
  ('Sydney', 'Australia',
    ARRAY['Home to the Sydney Opera House', 'Known for its beautiful beaches'],
    ARRAY['Sydney Opera House is one of the most recognizable buildings in the world', 'Sydney Harbour Bridge is known as the Coathanger'],
    ARRAY['Bondi Beach is a popular surfing destination', 'Sydney hosts the annual Mardi Gras parade']),
  ('Rome', 'Italy',
    ARRAY['Home to the Colosseum', 'Known as the Eternal City'],
    ARRAY['The Colosseum could hold up to 80,000 spectators', 'Rome was built on seven hills'],
    ARRAY['Famous for pasta carbonara', 'The Pantheon has a hole in its dome called the oculus']),
  ('Rio de Janeiro', 'Brazil',
    ARRAY['Home to Christ the Redeemer', 'Famous for Carnival'],
    ARRAY['Christ the Redeemer is 30 meters tall', 'Rio was once the capital of Portugal'],
    ARRAY['Copacabana Beach is a major tourist spot', 'Samba music originated here']),
  ('Cairo', 'Egypt',
    ARRAY['Home to the Great Pyramids', 'Located along the Nile River'],
    ARRAY['The Great Pyramid is one of the Seven Wonders', 'Cairo is nicknamed the City of a Thousand Minarets'],
    ARRAY['Famous for falafel and koshari', 'The Egyptian Museum houses Tutankhamun’s treasures']),
  ('Bangkok', 'Thailand',
    ARRAY['Known for its floating markets', 'Home to the Grand Palace'],
    ARRAY['Bangkok’s full name is the longest city name in the world', 'The city has over 400 temples'],
    ARRAY['Famous for pad thai', 'Street food markets operate 24/7']),
  ('London', 'United Kingdom',
    ARRAY['Home to Big Ben', 'Known for its red double-decker buses'],
    ARRAY['Big Ben is actually the nickname of the Great Bell', 'London Underground is the oldest subway system'],
    ARRAY['Famous for fish and chips', 'The city hosted the Olympics three times']),
  ('Cape Town', 'South Africa',
    ARRAY['Home to Table Mountain', 'Known for its vibrant waterfront'],
    ARRAY['Table Mountain is one of the New Seven Wonders of Nature', 'Cape Town was the first European settlement in South Africa'],
    ARRAY['Famous for bobotie', 'Robben Island was a prison for Nelson Mandela']),
  ('Moscow', 'Russia',
    ARRAY['Home to the Kremlin', 'Known for Saint Basil’s Cathedral'],
    ARRAY['Saint Basil’s Cathedral has nine domes', 'Moscow’s metro is one of the deepest in the world'],
    ARRAY['Famous for borscht', 'The city spans two continents: Europe and Asia']),
  ('Dubai', 'United Arab Emirates',
    ARRAY['Home to the Burj Khalifa', 'Known for its luxury shopping'],
    ARRAY['Burj Khalifa is the tallest building in the world', 'Dubai has no income tax'],
    ARRAY['Famous for gold souks', 'The city hosts an annual shopping festival']),
  ('Mumbai', 'India',
    ARRAY['Home to Bollywood', 'Known for its Gateway of India'],
    ARRAY['Mumbai was built on seven islands', 'The city’s train system carries over 7 million people daily'],
    ARRAY['Famous for vada pav', 'Marine Drive is nicknamed the Queen’s Necklace']),
  ('Mexico City', 'Mexico',
    ARRAY['Built on an ancient lake', 'Home to the Zócalo plaza'],
    ARRAY['Mexico City is sinking about 6-8 inches per year', 'The city was once the Aztec capital Tenochtitlán'],
    ARRAY['Famous for tacos al pastor', 'Hosts the Day of the Dead festival']),
  ('Istanbul', 'Turkey',
    ARRAY['Straddles Europe and Asia', 'Home to the Hagia Sophia'],
    ARRAY['Hagia Sophia was a church, mosque, and museum', 'Istanbul was once called Constantinople'],
    ARRAY['Famous for baklava', 'The Grand Bazaar is one of the oldest markets']),
  ('Seoul', 'South Korea',
    ARRAY['Known for K-pop culture', 'Home to Gyeongbokgung Palace'],
    ARRAY['Seoul has a 24/7 public transport system', 'The city hosted the 1988 Olympics'],
    ARRAY['Famous for kimchi', 'Han River is a popular recreational spot']),
  ('Barcelona', 'Spain',
    ARRAY['Home to Sagrada Família', 'Known for its Gaudí architecture'],
    ARRAY['Sagrada Família has been under construction since 1882', 'Barcelona has a beach in the city center'],
    ARRAY['Famous for paella', 'Hosts the annual La Mercè festival']),
  ('Havana', 'Cuba',
    ARRAY['Known for vintage cars', 'Home to the Malecón seawall'],
    ARRAY['Havana was founded in 1519', 'The city’s cigars are world-famous'],
    ARRAY['Famous for mojitos', 'Old Havana is a UNESCO World Heritage Site']),
  ('Vancouver', 'Canada',
    ARRAY['Surrounded by mountains and ocean', 'Home to Stanley Park'],
    ARRAY['Stanley Park is larger than Central Park', 'Vancouver is a major film production hub'],
    ARRAY['Famous for salmon dishes', 'Hosts the annual Celebration of Light']),
  ('Kyoto', 'Japan',
    ARRAY['Known for its ancient temples', 'Home to the Fushimi Inari Shrine'],
    ARRAY['Kyoto was Japan’s capital for over 1,000 years', 'The city has 17 UNESCO World Heritage Sites'],
    ARRAY['Famous for kaiseki cuisine', 'Geishas perform in Gion district']),
  ('Amsterdam', 'Netherlands',
    ARRAY['Known for its canals', 'Home to the Anne Frank House'],
    ARRAY['Amsterdam has more canals than Venice', 'The city’s bikes outnumber its residents'],
    ARRAY['Famous for stroopwafels', 'Hosts the annual King’s Day celebration']),
  ('Lima', 'Peru',
    ARRAY['Known for its culinary scene', 'Home to the Plaza de Armas'],
    ARRAY['Lima was the capital of the Spanish Americas', 'The city sits on a desert coast'],
    ARRAY['Famous for ceviche', 'Miraflores is a popular tourist district']),
  ('Singapore', 'Singapore',
    ARRAY['Known for Marina Bay Sands', 'Famous for its cleanliness'],
    ARRAY['Singapore has no chewing gum sales', 'Gardens by the Bay has futuristic supertrees'],
    ARRAY['Famous for chili crab', 'The city-state has four official languages']),
  ('Athens', 'Greece',
    ARRAY['Home to the Acropolis', 'Known as the cradle of Western civilization'],
    ARRAY['The Parthenon was built in the 5th century BC', 'Athens hosted the first modern Olympics'],
    ARRAY['Famous for souvlaki', 'The city’s metro uncovers ancient artifacts']),
  ('Buenos Aires', 'Argentina',
    ARRAY['Known for tango dancing', 'Home to the Obelisk'],
    ARRAY['Buenos Aires has the widest avenue in the world', 'The city is called the Paris of South America'],
    ARRAY['Famous for asado barbecue', 'La Boca is known for colorful houses']),
  ('Prague', 'Czech Republic',
    ARRAY['Known for its castle', 'Home to the Charles Bridge'],
    ARRAY['Prague Castle is the largest ancient castle', 'The city avoided major WWII destruction'],
    ARRAY['Famous for goulash', 'Hosts a famous Christmas market']),
  ('Nairobi', 'Kenya',
    ARRAY['Gateway to safari adventures', 'Home to Nairobi National Park'],
    ARRAY['Nairobi is one of Africa’s tech hubs', 'The park is just 7 km from the city center'],
    ARRAY['Famous for nyama choma', 'The city hosts the Safari Rally']),
  ('Reykjavik', 'Iceland',
    ARRAY['Known for the Northern Lights', 'Home to Hallgrímskirkja church'],
    ARRAY['Reykjavik runs on geothermal energy', 'The city has no Starbucks'],
    ARRAY['Famous for skyr yogurt', 'Hosts the Iceland Airwaves festival']),
  ('Lisbon', 'Portugal',
    ARRAY['Known for its trams', 'Home to Belém Tower'],
    ARRAY['Lisbon’s tram 28 is a tourist attraction', 'The city was rebuilt after a 1755 earthquake'],
    ARRAY['Famous for pastéis de nata', 'The Tagus River runs through it']),
  ('Hanoi', 'Vietnam',
    ARRAY['Known for its Old Quarter', 'Home to Hoan Kiem Lake'],
    ARRAY['Hanoi’s train street has trains passing through homes', 'The city was the capital of French Indochina'],
    ARRAY['Famous for pho', 'Hosts a vibrant night market']),
  ('Edinburgh', 'Scotland',
    ARRAY['Home to Edinburgh Castle', 'Known for its Fringe Festival'],
    ARRAY['The castle sits on an extinct volcano', 'Edinburgh inspired Hogwarts in Harry Potter'],
    ARRAY['Famous for haggis', 'The city has a haunted underground vault']),
  ('Jerusalem', 'Israel',
    ARRAY['Home to the Western Wall', 'Sacred to three religions'],
    ARRAY['Jerusalem is over 3,000 years old', 'The city has a golden-domed shrine'],
    ARRAY['Famous for hummus', 'The Old City is a UNESCO World Heritage Site']),
  ('Santiago', 'Chile',
    ARRAY['Surrounded by the Andes', 'Home to Plaza de Armas'],
    ARRAY['Santiago was founded in 1541', 'The city has a vibrant street art scene'],
    ARRAY['Famous for empanadas', 'Cerro San Cristóbal offers panoramic views']),
  ('Vienna', 'Austria',
    ARRAY['Known for its coffee houses', 'Home to Schönbrunn Palace'],
    ARRAY['Vienna was home to Mozart and Beethoven', 'The city’s waltz is world-famous'],
    ARRAY['Famous for schnitzel', 'Hosts the Vienna Opera Ball']),
  ('Kuala Lumpur', 'Malaysia',
    ARRAY['Home to the Petronas Towers', 'Known for its night markets'],
    ARRAY['Petronas Towers were the tallest buildings until 2004', 'The city blends Malay, Chinese, and Indian cultures'],
    ARRAY['Famous for nasi lemak', 'Batu Caves is a nearby Hindu shrine']),
  ('Bogotá', 'Colombia',
    ARRAY['Located in a high plateau', 'Home to the Gold Museum'],
    ARRAY['Bogotá is 2,640 meters above sea level', 'The city’s graffiti is a tourist attraction'],
    ARRAY['Famous for ajiaco soup', 'Hosts the Ibero-American Theater Festival']),
  ('Stockholm', 'Sweden',
    ARRAY['Built on 14 islands', 'Home to the Vasa Museum'],
    ARRAY['The Vasa ship sank on its maiden voyage', 'Stockholm hosted the 1912 Olympics'],
    ARRAY['Famous for meatballs', 'The city has a metro art gallery']),
  ('Jakarta', 'Indonesia',
    ARRAY['Known for its vibrant street food', 'Home to Merdeka Square'],
    ARRAY['Jakarta is sinking due to groundwater extraction', 'The city was once called Batavia'],
    ARRAY['Famous for nasi goreng', 'Hosts the Java Jazz Festival']),
  ('Montreal', 'Canada',
    ARRAY['Known for its French culture', 'Home to Mount Royal'],
    ARRAY['Montreal has an underground city', 'The city hosted the 1976 Olympics'],
    ARRAY['Famous for poutine', 'Hosts the Just for Laughs comedy festival']),
  ('Casablanca', 'Morocco',
    ARRAY['Home to the Hassan II Mosque', 'Known for its Art Deco architecture'],
    ARRAY['The mosque has the tallest minaret in the world', 'Casablanca inspired a famous 1942 film'],
    ARRAY['Famous for tagine', 'The city is Morocco’s economic hub']),
  ('Kyiv', 'Ukraine',
    ARRAY['Home to Saint Sophia’s Cathedral', 'Known for its golden domes'],
    ARRAY['Kyiv is one of Europe’s oldest cities', 'The city’s metro is one of the deepest'],
    ARRAY['Famous for borscht', 'Hosts the annual Kyiv Day']),
  ('Manila', 'Philippines',
    ARRAY['Known for its historic Intramuros', 'Home to Rizal Park'],
    ARRAY['Manila was heavily damaged in WWII', 'The city is named after a white flower'],
    ARRAY['Famous for adobo', 'Jeepneys are a unique mode of transport']),
  ('Auckland', 'New Zealand',
    ARRAY['Known as the City of Sails', 'Home to Sky Tower'],
    ARRAY['Sky Tower is the tallest in the Southern Hemisphere', 'Auckland has 50 volcanic cones'],
    ARRAY['Famous for pavlova', 'Hosts the Pasifika Festival']),
  ('Lagos', 'Nigeria',
    ARRAY['Known for its vibrant music scene', 'Home to the Third Mainland Bridge'],
    ARRAY['Lagos is Africa’s most populous city', 'The bridge is one of the longest in Africa'],
    ARRAY['Famous for jollof rice', 'Nollywood films are produced here']),
  ('San Francisco', 'USA',
    ARRAY['Home to the Golden Gate Bridge', 'Known for its steep hills'],
    ARRAY['The bridge was completed in 1937', 'San Francisco is part of Silicon Valley'],
    ARRAY['Famous for clam chowder', 'Alcatraz was a notorious prison']),
  ('Marrakech', 'Morocco',
    ARRAY['Known for its souks', 'Home to Jemaa el-Fnaa square'],
    ARRAY['Marrakech is called the Red City', 'The square is a UNESCO cultural site'],
    ARRAY['Famous for couscous', 'The city has historic riads']),
  ('Oslo', 'Norway',
    ARRAY['Known for its fjords', 'Home to the Viking Ship Museum'],
    ARRAY['Oslo awards the Nobel Peace Prize', 'The city has a sculpture park with 200 statues'],
    ARRAY['Famous for salmon', 'Hosts the annual Holmenkollen Ski Festival']),
  ('Panama City', 'Panama',
    ARRAY['Home to the Panama Canal', 'Known for its modern skyline'],
    ARRAY['The canal connects two oceans', 'Panama City was founded in 1519'],
    ARRAY['Famous for sancocho', 'The city has a historic Casco Viejo']),
  ('Addis Ababa', 'Ethiopia',
    ARRAY['Home to the African Union headquarters', 'Known for its coffee culture'],
    ARRAY['Addis Ababa means New Flower', 'The city is at 2,355 meters elevation'],
    ARRAY['Famous for injera', 'Hosts the Great Ethiopian Run']),
  ('Tehran', 'Iran',
    ARRAY['Known for its bazaars', 'Home to the Golestan Palace'],
    ARRAY['Tehran is at the foot of the Alborz Mountains', 'The palace is a UNESCO site'],
    ARRAY['Famous for kebabs', 'The city has a vibrant café culture']),
  ('San Juan', 'Puerto Rico',
    ARRAY['Known for its colorful colonial buildings', 'Home to El Morro fortress'],
    ARRAY['El Morro was built in the 16th century', 'San Juan is the oldest city under U.S. jurisdiction'],
    ARRAY['Famous for mofongo', 'Hosts the San Sebastián Street Festival']),
  ('Colombo', 'Sri Lanka',
    ARRAY['Known for its coastal location', 'Home to the Gangaramaya Temple'],
    ARRAY['Colombo was a major spice trade hub', 'The city blends colonial and modern architecture'],
    ARRAY['Famous for kottu roti', 'The Lotus Tower is South Asia’s tallest']),
  ('Tunis', 'Tunisia',
    ARRAY['Known for its medina', 'Home to the Bardo Museum'],
    ARRAY['The medina is a UNESCO World Heritage Site', 'Tunis was once a major Carthaginian city'],
    ARRAY['Famous for shakshuka', 'The city hosts the Carthage Film Festival']),
  ('Caracas', 'Venezuela',
    ARRAY['Surrounded by mountains', 'Home to the Ávila National Park'],
    ARRAY['Caracas was founded in 1567', 'The city has a cable car to Mount Ávila'],
    ARRAY['Famous for arepas', 'The birthplace of Simón Bolívar']),
  ('Kathmandu', 'Nepal',
    ARRAY['Gateway to the Himalayas', 'Home to Swayambhunath Stupa'],
    ARRAY['Kathmandu Valley has seven UNESCO sites', 'The city is at 1,400 meters elevation'],
    ARRAY['Famous for momos', 'Hosts the Dashain festival']),
  ('Accra', 'Ghana',
    ARRAY['Known for its vibrant markets', 'Home to Independence Arch'],
    ARRAY['Accra is a major African fashion hub', 'The city was the capital of the Gold Coast'],
    ARRAY['Famous for fufu', 'Hosts the Chale Wote Street Art Festival']),
  ('Belgrade', 'Serbia',
    ARRAY['Located at the confluence of two rivers', 'Home to Kalemegdan Fortress'],
    ARRAY['Belgrade was a Roman city called Singidunum', 'The fortress offers panoramic views'],
    ARRAY['Famous for ćevapi', 'Hosts the Belgrade Beer Fest']),
  ('Montevideo', 'Uruguay',
    ARRAY['Known for its long coastline', 'Home to Plaza Independencia'],
    ARRAY['Montevideo hosted the first FIFA World Cup', 'The city has a 22-km beach promenade'],
    ARRAY['Famous for chivito', 'The Carnival is a major event']),
  ('Riga', 'Latvia',
    ARRAY['Known for its Art Nouveau architecture', 'Home to the House of the Blackheads'],
    ARRAY['Riga’s old town is a UNESCO site', 'The city was a major Hanseatic League member'],
    ARRAY['Famous for rye bread', 'Hosts the Latvian Song and Dance Festival']),
  ('Tbilisi', 'Georgia',
    ARRAY['Known for its sulfur baths', 'Home to Narikala Fortress'],
    ARRAY['Tbilisi was founded in the 5th century', 'The city’s name means warm place'],
    ARRAY['Famous for khachapuri', 'The Old Town has colorful balconies']),
  ('Ulaanbaatar', 'Mongolia',
    ARRAY['Known for its nomadic heritage', 'Home to Gandan Monastery'],
    ARRAY['Ulaanbaatar is the coldest capital city', 'The city was a mobile monastery until 1778'],
    ARRAY['Famous for buuz dumplings', 'Hosts the Naadam Festival']),
  ('Sofia', 'Bulgaria',
    ARRAY['Home to Alexander Nevsky Cathedral', 'Known for its mineral springs'],
    ARRAY['Sofia is one of Europe’s oldest cities', 'The cathedral can hold 10,000 people'],
    ARRAY['Famous for banitsa', 'Vitosha Mountain is nearby']),
  ('Helsinki', 'Finland',
    ARRAY['Known for its archipelago', 'Home to Suomenlinna Fortress'],
    ARRAY['Suomenlinna is a UNESCO site', 'Helsinki has 330 islands'],
    ARRAY['Famous for reindeer dishes', 'Hosts the Helsinki Festival']),
  ('San José', 'Costa Rica',
    ARRAY['Known for its coffee plantations', 'Home to the National Theatre'],
    ARRAY['San José is in a volcanic valley', 'The theatre was built with coffee tax money'],
    ARRAY['Famous for gallo pinto', 'The city is a hub for eco-tourism']),
  ('Guatemala City', 'Guatemala',
    ARRAY['Known for its Mayan heritage', 'Home to the National Palace'],
    ARRAY['The city was founded in 1776', 'It’s surrounded by four volcanoes'],
    ARRAY['Famous for tamales', 'Hosts the Fiesta de Santo Tomás']),
  ('Baku', 'Azerbaijan',
    ARRAY['Known for its Flame Towers', 'Home to the Old City'],
    ARRAY['Baku’s Old City is a UNESCO site', 'The city is below sea level'],
    ARRAY['Famous for plov', 'Hosts the Baku Jazz Festival']),
  ('Dhaka', 'Bangladesh',
    ARRAY['Known for its rickshaws', 'Home to Lalbagh Fort'],
    ARRAY['Dhaka is one of the most densely populated cities', 'The fort was built in the 17th century'],
    ARRAY['Famous for biryani', 'The Buriganga River runs through it']),
  ('La Paz', 'Bolivia',
    ARRAY['Highest capital city in the world', 'Home to the Witches’ Market'],
    ARRAY['La Paz is at 3,640 meters elevation', 'The city has a cable car system'],
    ARRAY['Famous for salteñas', 'The Valley of the Moon is nearby']),
  ('Phnom Penh', 'Cambodia',
    ARRAY['Known for its Royal Palace', 'Located along the Mekong River'],
    ARRAY['The palace has a silver pagoda', 'Phnom Penh was once the Pearl of Asia'],
    ARRAY['Famous for amok curry', 'The Killing Fields are a historical site']),
  ('Dakar', 'Senegal',
    ARRAY['Known for its vibrant music', 'Home to Gorée Island'],
    ARRAY['Gorée Island was a slave trade hub', 'Dakar hosts the Dakar Rally'],
    ARRAY['Famous for thiéboudienne', 'The African Renaissance Monument is iconic']),
  ('Tirana', 'Albania',
    ARRAY['Known for its colorful buildings', 'Home to Skanderbeg Square'],
    ARRAY['Tirana’s buildings were painted to boost morale', 'The city was under Ottoman rule for centuries'],
    ARRAY['Famous for byrek', 'The Bunk’Art museum is unique']),
  ('Quito', 'Ecuador',
    ARRAY['Located in the Andes', 'Home to the Basilica del Voto Nacional'],
    ARRAY['Quito was the first UNESCO World Heritage City', 'The city is at 2,850 meters elevation'],
    ARRAY['Famous for locro soup', 'The equator runs nearby']),
  ('Muscat', 'Oman',
    ARRAY['Known for its waterfront souq', 'Home to the Sultan Qaboos Mosque'],
    ARRAY['The mosque can hold 20,000 worshippers', 'Muscat was a major trading port'],
    ARRAY['Famous for shuwa', 'The city is surrounded by mountains']),
  ('Bratislava', 'Slovakia',
    ARRAY['Located along the Danube', 'Home to Bratislava Castle'],
    ARRAY['Bratislava borders two countries', 'The castle dates back to the 9th century'],
    ARRAY['Famous for bryndzové halušky', 'The UFO Bridge is iconic']),
  ('Maputo', 'Mozambique',
    ARRAY['Known for its colonial architecture', 'Home to the Iron House'],
    ARRAY['The Iron House was designed by Gustave Eiffel', 'Maputo was called Lourenço Marques'],
    ARRAY['Famous for peri-peri prawns', 'The city hosts the Maputo International Music Festival']),
  ('Windhoek', 'Namibia',
    ARRAY['Known for its German colonial buildings', 'Home to Christuskirche'],
    ARRAY['Windhoek is in a desert valley', 'The city’s name means windy corner'],
    ARRAY['Famous for biltong', 'The Namib Desert is nearby']),
  ('Port Louis', 'Mauritius',
    ARRAY['Known for its waterfront', 'Home to the Aapravasi Ghat'],
    ARRAY['Aapravasi Ghat is a UNESCO site', 'Port Louis was a major sugar trade hub'],
    ARRAY['Famous for dholl puri', 'The Caudan Waterfront is a popular spot']),
  ('Yerevan', 'Armenia',
    ARRAY['Known for its pink tuff buildings', 'Home to the Cascade complex'],
    ARRAY['Yerevan is one of the world’s oldest cities', 'The city is at the foot of Mount Ararat'],
    ARRAY['Famous for lavash bread', 'Hosts the Yerevan Wine Days']),
  ('Vientiane', 'Laos',
    ARRAY['Known for its Buddhist temples', 'Home to Pha That Luang'],
    ARRAY['Pha That Luang is the national symbol', 'Vientiane is along the Mekong River'],
    ARRAY['Famous for sticky rice', 'The night market is a tourist attraction']),
  ('Bishkek', 'Kyrgyzstan',
    ARRAY['Known for its Soviet architecture', 'Home to Ala-Too Square'],
    ARRAY['Bishkek was called Frunze during Soviet times', 'The city is near the Tian Shan mountains'],
    ARRAY['Famous for laghman noodles', 'Hosts the World Nomad Games']),
  ('Suva', 'Fiji',
    ARRAY['Known for its tropical setting', 'Home to the Fiji Museum'],
    ARRAY['Suva is the political capital of the Pacific', 'The museum houses 3,000-year-old artifacts'],
    ARRAY['Famous for kokoda', 'The city hosts the Hibiscus Festival']),
  ('Luxembourg City', 'Luxembourg',
    ARRAY['Known for its medieval fortifications', 'Home to the Bock Casemates'],
    ARRAY['The casemates are a UNESCO site', 'Luxembourg is one of the smallest countries'],
    ARRAY['Famous for judd mat gaardebounen', 'The city is a financial hub']),
  ('Nicosia', 'Cyprus',
    ARRAY['Known for its divided capital', 'Home to the Ledra Street crossing'],
    ARRAY['Nicosia is the last divided capital in Europe', 'The city has Venetian walls'],
    ARRAY['Famous for souvlaki', 'The Cyprus Museum is a major attraction']),
  ('Kingston', 'Jamaica',
    ARRAY['Known for its reggae music', 'Home to the Bob Marley Museum'],
    ARRAY['Kingston was Jamaica’s capital since 1872', 'The city is a UNESCO Creative City'],
    ARRAY['Famous for jerk chicken', 'Port Royal was a pirate hub']),
  ('Astana', 'Kazakhstan',
    ARRAY['Known for its futuristic architecture', 'Home to the Bayterek Tower'],
    ARRAY['Astana became the capital in 1997', 'The city was renamed Nur-Sultan and back'],
    ARRAY['Famous for beshbarmak', 'The Palace of Peace is a pyramid-shaped building']),
  ('San Salvador', 'El Salvador',
    ARRAY['Known for its volcanic backdrop', 'Home to the National Palace'],
    ARRAY['San Salvador was destroyed by earthquakes multiple times', 'The city is near Lake Ilopango'],
    ARRAY['Famous for pupusas', 'The Joya de Cerén is a Mayan Pompeii']),
  ('Harare', 'Zimbabwe',
    ARRAY['Known for its jacaranda trees', 'Home to the National Gallery'],
    ARRAY['Harare was founded as Fort Salisbury', 'The city hosts the Harare International Festival'],
    ARRAY['Famous for sadza', 'The Kopje offers city views']),
  ('Lusaka', 'Zambia',
    ARRAY['Known for its markets', 'Home to the Freedom Statue'],
    ARRAY['Lusaka was planned as a garden city', 'The city is a hub for copper trade'],
    ARRAY['Famous for nshima', 'The nearby Lower Zambezi is a safari destination']),
  ('Kigali', 'Rwanda',
    ARRAY['Known for its cleanliness', 'Home to the Kigali Genocide Memorial'],
    ARRAY['Kigali is one of Africa’s safest cities', 'The city is built on hills'],
    ARRAY['Famous for brochettes', 'Hosts the KigaliUp Music Festival']),
  ('Porto', 'Portugal',
    ARRAY['Known for its port wine', 'Home to the Ribeira District'],
    ARRAY['Porto’s Livraria Lello inspired Harry Potter', 'The city’s bridges are iconic'],
    ARRAY['Famous for francesinha', 'The Douro River runs through it']),
  ('Valletta', 'Malta',
    ARRAY['Known for its fortified walls', 'Home to St. John’s Co-Cathedral'],
    ARRAY['Valletta is a UNESCO World Heritage City', 'The city was built by the Knights of Malta'],
    ARRAY['Famous for pastizzi', 'The Grand Harbour is a historic port']),
  ('Chiang Mai', 'Thailand',
    ARRAY['Known for its ancient temples', 'Home to Doi Suthep'],
    ARRAY['Chiang Mai was the capital of the Lanna Kingdom', 'The city hosts a lantern festival'],
    ARRAY['Famous for khao soi', 'The Night Bazaar is a popular market']),
  ('Luanda', 'Angola',
    ARRAY['Known for its coastal promenade', 'Home to the Fortress of São Miguel'],
    ARRAY['Luanda is Africa’s most expensive city', 'The fortress was built in 1576'],
    ARRAY['Famous for funje', 'The city hosts the Luanda Jazz Festival']),
  ('Asunción', 'Paraguay',
    ARRAY['Known for its colonial heritage', 'Home to the Palacio de los López'],
    ARRAY['Asunción was founded in 1537', 'The city is along the Paraguay River'],
    ARRAY['Famous for chipa', 'The Ñandutí lace is a traditional craft']),
  ('Gaborone', 'Botswana',
    ARRAY['Known for its modern architecture', 'Home to the Three Dikgosi Monument'],
    ARRAY['Gaborone was founded in 1964', 'The city is near the Kalahari Desert'],
    ARRAY['Famous for seswaa', 'The Okavango Delta is a nearby attraction']),
  ('Minsk', 'Belarus',
    ARRAY['Known for its Soviet architecture', 'Home to the National Library'],
    ARRAY['The library is shaped like a rhombicosidodecahedron', 'Minsk was rebuilt after WWII'],
    ARRAY['Famous for draniki', 'The city hosts the Minsk Film Festival']),
  ('Islamabad', 'Pakistan',
    ARRAY['Known for its planned layout', 'Home to Faisal Mosque'],
    ARRAY['Faisal Mosque is one of the largest in the world', 'Islamabad was built in the 1960s'],
    ARRAY['Famous for nihari', 'The Margalla Hills are a popular hiking spot']),
  ('Doha', 'Qatar',
    ARRAY['Known for its futuristic skyline', 'Home to the Museum of Islamic Art'],
    ARRAY['Doha hosted the 2022 FIFA World Cup', 'The city is on a pearl-diving coast'],
    ARRAY['Famous for machboos', 'The Souq Waqif is a traditional market']),
  ('Dar es Salaam', 'Tanzania',
    ARRAY['Known for its harbor', 'Home to the National Museum'],
    ARRAY['Dar es Salaam means Haven of Peace', 'The city was Tanzania’s capital until 1996'],
    ARRAY['Famous for ugali', 'The nearby Zanzibar is a spice island']),
  ('Antananarivo', 'Madagascar',
    ARRAY['Known for its hilly landscape', 'Home to the Rova of Antananarivo'],
    ARRAY['The Rova is a royal palace complex', 'Antananarivo was founded in the 17th century'],
    ARRAY['Famous for romazava', 'The city’s markets sell zebu meat']),
  ('Lilongwe', 'Malawi',
    ARRAY['Known for its nature reserves', 'Home to the Lilongwe Wildlife Centre'],
    ARRAY['Lilongwe became the capital in 1975', 'The city is named after a river'],
    ARRAY['Famous for nsima', 'The nearby Lake Malawi is a UNESCO site']),
  ('Thimphu', 'Bhutan',
    ARRAY['Known for its Buddhist monasteries', 'Home to Tashichho Dzong'],
    ARRAY['Thimphu has no traffic lights', 'The city is at 2,320 meters elevation'],
    ARRAY['Famous for ema datshi', 'The Dochula Pass has 108 stupas']),
  ('Apia', 'Samoa',
    ARRAY['Known for its tropical beaches', 'Home to the Robert Louis Stevenson Museum'],
    ARRAY['Apia was home to the author of Treasure Island', 'The city is on Upolu Island'],
    ARRAY['Famous for oka', 'The Palolo Deep Marine Reserve is nearby']),
  ('Bridgetown', 'Barbados',
    ARRAY['Known for its historic garrison', 'Home to Carlisle Bay'],
    ARRAY['Bridgetown is a UNESCO World Heritage Site', 'The city was founded in 1628'],
    ARRAY['Famous for flying fish', 'The Crop Over festival is a major event']),
  ('Podgorica', 'Montenegro',
    ARRAY['Known for its Ottoman heritage', 'Home to the Millennium Bridge'],
    ARRAY['Podgorica was called Titograd during Yugoslav times', 'The city is at the confluence of two rivers'],
    ARRAY['Famous for kacamak', 'The nearby Lake Skadar is a national park']),
  ('Nouakchott', 'Mauritania',
    ARRAY['Known for its desert surroundings', 'Home to the National Museum'],
    ARRAY['Nouakchott was a small village until 1958', 'The city is near the Atlantic coast'],
    ARRAY['Famous for thieboudienne', 'The Banc d’Arguin is a nearby UNESCO site']),
  ('Malé', 'Maldives',
    ARRAY['Known for its turquoise waters', 'Home to the Old Friday Mosque'],
    ARRAY['Malé is one of the smallest capitals', 'The city is threatened by rising sea levels'],
    ARRAY['Famous for mas huni', 'The artificial beach is a popular spot']),
  ('Port Moresby', 'Papua New Guinea',
    ARRAY['Known for its coastal location', 'Home to the National Museum'],
    ARRAY['Port Moresby hosted the 2015 Pacific Games', 'The city is on the Gulf of Papua'],
    ARRAY['Famous for mumu', 'The Variarata National Park is nearby']),
  ('Algiers', 'Algeria',
    ARRAY['Known for its white-washed buildings', 'Home to the Casbah'],
    ARRAY['The Casbah is a UNESCO World Heritage Site', 'Algiers was a pirate stronghold'],
    ARRAY['Famous for couscous', 'The Martyrs’ Memorial is iconic']),
  ('Amman', 'Jordan',
    ARRAY['Known for its ancient ruins', 'Home to the Roman Theatre'],
    ARRAY['Amman was called Philadelphia in Roman times', 'The city is built on seven hills'],
    ARRAY['Famous for mansaf', 'The nearby Dead Sea is the lowest point on Earth']),
  ('Belfast', 'Northern Ireland',
    ARRAY['Known for its shipbuilding history', 'Home to the Titanic Belfast'],
    ARRAY['The Titanic was built in Belfast', 'The city has a vibrant mural scene'],
    ARRAY['Famous for Ulster fry', 'The Giant’s Causeway is a nearby attraction']),
  ('Cardiff', 'Wales',
    ARRAY['Known for its castle', 'Home to the Principality Stadium'],
    ARRAY['Cardiff Castle has Roman origins', 'The city is the capital of Wales'],
    ARRAY['Famous for Welsh cakes', 'The Cardiff Bay is a redeveloped waterfront']),
  ('Dili', 'Timor-Leste',
    ARRAY['Known for its beaches', 'Home to the Cristo Rei statue'],
    ARRAY['Dili was occupied by Indonesia until 2002', 'The statue is a gift from Indonesia'],
    ARRAY['Famous for ikan pepes', 'The Tais Market sells traditional textiles']),
  ('Freetown', 'Sierra Leone',
    ARRAY['Known for its cotton tree', 'Home to the Sierra Leone National Museum'],
    ARRAY['The cotton tree is a symbol of freedom', 'Freetown was founded by freed slaves'],
    ARRAY['Famous for groundnut stew', 'Lumley Beach is a popular spot']),
  ('Gaborone', 'Botswana',
    ARRAY['Known for its modern architecture', 'Home to the Three Dikgosi Monument'],
    ARRAY['Gaborone was founded in 1964', 'The city is near the Kalahari Desert'],
    ARRAY['Famous for seswaa', 'The Okavango Delta is a nearby attraction']),
  ('Hargeisa', 'Somaliland',
    ARRAY['Known for its livestock market', 'Home to the Laas Geel caves'],
    ARRAY['Laas Geel has 5,000-year-old rock art', 'Hargeisa is a self-declared republic'],
    ARRAY['Famous for camel milk', 'The MiG jet monument commemorates a war']),
  ('Kampala', 'Uganda',
    ARRAY['Known for its seven hills', 'Home to the Kasubi Tombs'],
    ARRAY['The tombs are a UNESCO site', 'Kampala is near Lake Victoria'],
    ARRAY['Famous for matoke', 'The Uganda Museum is a cultural hub']),
  ('Kuwait City', 'Kuwait',
    ARRAY['Known for its modern towers', 'Home to the Kuwait Towers'],
    ARRAY['The towers were opened in 1979', 'Kuwait City is a major oil hub'],
    ARRAY['Famous for machboos', 'The Souk Al-Mubarakiya is a historic market']),
  ('Ljubljana', 'Slovenia',
    ARRAY['Known for its green spaces', 'Home to the Triple Bridge'],
    ARRAY['Ljubljana was named Europe’s Green Capital', 'The city’s castle is on a hill'],
    ARRAY['Famous for štruklji', 'The Ljubljanica River runs through it']),
  ('Monrovia', 'Liberia',
    ARRAY['Known for its beaches', 'Home to the Centennial Pavilion'],
    ARRAY['Monrovia was named after President Monroe', 'The city was founded by freed slaves'],
    ARRAY['Famous for palm butter soup', 'Providence Island is a historic site']),
  ('Nassau', 'Bahamas',
    ARRAY['Known for its pink sand beaches', 'Home to the Queen’s Staircase'],
    ARRAY['The staircase was carved by slaves', 'Nassau is a cruise ship hub'],
    ARRAY['Famous for conch fritters', 'The Junkanoo festival is vibrant']),
  ('Ottawa', 'Canada',
    ARRAY['Known for its Parliament Hill', 'Home to the Rideau Canal'],
    ARRAY['The canal is a UNESCO site', 'Ottawa is Canada’s capital'],
    ARRAY['Famous for beaver tails', 'The city hosts the Winterlude festival']),
  ('Paramaribo', 'Suriname',
    ARRAY['Known for its Dutch colonial architecture', 'Home to the Saint Peter and Paul Cathedral'],
    ARRAY['The cathedral is made of wood', 'Paramaribo is a UNESCO site'],
    ARRAY['Famous for pom', 'The Suriname River runs through it']),
  ('Port of Spain', 'Trinidad and Tobago',
    ARRAY['Known for its Carnival', 'Home to the Queen’s Park Savannah'],
    ARRAY['Carnival is one of the largest in the Caribbean', 'The city was founded by the Spanish'],
    ARRAY['Famous for doubles', 'The Magnificent Seven are historic mansions']),
  ('Port Vila', 'Vanuatu',
    ARRAY['Known for its coral reefs', 'Home to the National Museum'],
    ARRAY['Port Vila is on Efate Island', 'The city was a WWII Allied base'],
    ARRAY['Famous for laplap', 'The Mele Cascades are a nearby attraction']),
  ('Rabat', 'Morocco',
    ARRAY['Known for its historic kasbah', 'Home to the Hassan Tower'],
    ARRAY['The tower is an unfinished minaret', 'Rabat is a UNESCO site'],
    ARRAY['Famous for harira', 'The Chellah necropolis is a historic site']),
  ('Riyadh', 'Saudi Arabia',
    ARRAY['Known for its modern skyscrapers', 'Home to the Al Rajhi Grand Mosque'],
    ARRAY['Riyadh Season is a major cultural festival', 'The city is in a desert oasis'],
    ARRAY['Famous for kabsa', 'The National Museum is a cultural hub']),
  ('Roseau', 'Dominica',
    ARRAY['Known for its boiling lake', 'Home to the Dominica Museum'],
    ARRAY['The boiling lake is a natural hot spring', 'Roseau is on the Caribbean coast'],
    ARRAY['Famous for callaloo', 'The Morne Trois Pitons is a UNESCO site']),
  ('Saint Petersburg', 'Russia',
    ARRAY['Known for its canals', 'Home to the Hermitage Museum'],
    ARRAY['The Hermitage is one of the largest museums', 'The city was Russia’s capital until 1918'],
    ARRAY['Famous for pelmeni', 'The White Nights festival is unique']),
  ('San Marino', 'San Marino',
    ARRAY['Known for its medieval towers', 'Home to Mount Titano'],
    ARRAY['San Marino is one of the smallest countries', 'The city is a UNESCO site'],
    ARRAY['Famous for torta tre monti', 'The Three Towers are iconic']),
  ('Santo Domingo', 'Dominican Republic',
    ARRAY['Known for its colonial zone', 'Home to the Catedral Primada'],
    ARRAY['The cathedral is the oldest in the Americas', 'Santo Domingo was founded in 1496'],
    ARRAY['Famous for mangu', 'The Malecón is a popular promenade']),
  ('Sarajevo', 'Bosnia and Herzegovina',
    ARRAY['Known for its Ottoman heritage', 'Home to the Latin Bridge'],
    ARRAY['The bridge was the site of Archduke Franz Ferdinand’s assassination', 'Sarajevo hosted the 1984 Winter Olympics'],
    ARRAY['Famous for cevapi', 'The city blends East and West cultures']),
  ('Seville', 'Spain',
    ARRAY['Known for its flamenco', 'Home to the Alcázar of Seville'],
    ARRAY['The Alcázar is a UNESCO site', 'Seville hosted the 1992 Expo'],
    ARRAY['Famous for gazpacho', 'The Plaza de España is iconic']),
  ('Skopje', 'North Macedonia',
    ARRAY['Known for its stone bridge', 'Home to the Mother Teresa Memorial'],
    ARRAY['Mother Teresa was born in Skopje', 'The city has a statue-building project'],
    ARRAY['Famous for tavče gravče', 'The Kale Fortress offers city views']),
  ('Taipei', 'Taiwan',
    ARRAY['Known for its night markets', 'Home to Taipei 101'],
    ARRAY['Taipei 101 was the tallest building until 2010', 'The city has a vibrant street food scene'],
    ARRAY['Famous for beef noodle soup', 'The Chiang Kai-shek Memorial is iconic']),
  ('Tallinn', 'Estonia',
    ARRAY['Known for its medieval old town', 'Home to Alexander Nevsky Cathedral'],
    ARRAY['Tallinn’s old town is a UNESCO site', 'The city is a digital innovation hub'],
    ARRAY['Famous for black bread', 'The Song Festival is a cultural event']),
  ('Tashkent', 'Uzbekistan',
    ARRAY['Known for its Silk Road history', 'Home to the Chorsu Bazaar'],
    ARRAY['Tashkent’s metro is an architectural marvel', 'The city was rebuilt after a 1966 earthquake'],
    ARRAY['Famous for plov', 'The Amir Timur Museum is a landmark']),
  ('Tegucigalpa', 'Honduras',
    ARRAY['Known for its colonial churches', 'Home to the National Gallery'],
    ARRAY['Tegucigalpa means silver hill', 'The city is in a valley'],
    ARRAY['Famous for baleadas', 'The Picacho Hill offers city views']),
  ('Tripoli', 'Libya',
    ARRAY['Known for its historic medina', 'Home to the Arch of Marcus Aurelius'],
    ARRAY['The arch dates to the 2nd century', 'Tripoli was a Phoenician city'],
    ARRAY['Famous for shorba', 'The Red Castle Museum is a landmark']),
  ('Vaduz', 'Liechtenstein',
    ARRAY['Known for its castle', 'Home to the Kunstmuseum'],
    ARRAY['Vaduz is one of the smallest capitals', 'The castle is the prince’s residence'],
    ARRAY['Famous for käsknöpfle', 'The Rhine River borders the city']),
  ('Victoria', 'Seychelles',
    ARRAY['Known for its tropical beaches', 'Home to the Victoria Clocktower'],
    ARRAY['Victoria is one of the smallest capitals', 'The city is on Mahé Island'],
    ARRAY['Famous for fish curry', 'The Morne Seychellois National Park is nearby']),
  ('Vilnius', 'Lithuania',
    ARRAY['Known for its baroque architecture', 'Home to Gediminas’ Tower'],
    ARRAY['Vilnius’ old town is a UNESCO site', 'The city was once called the Jerusalem of the North'],
    ARRAY['Famous for cepelinai', 'The Užupis district is a self-proclaimed republic']),
  ('Warsaw', 'Poland',
    ARRAY['Known for its reconstructed old town', 'Home to the Royal Castle'],
    ARRAY['The old town was rebuilt after WWII', 'Warsaw hosted Chopin’s concerts'],
    ARRAY['Famous for pierogi', 'The Vistula River runs through it']),
  ('Yamoussoukro', 'Ivory Coast',
    ARRAY['Known for its oversized basilica', 'Home to the Basilica of Our Lady of Peace'],
    ARRAY['The basilica is larger than St. Peter’s in Rome', 'Yamoussoukro is the political capital'],
    ARRAY['Famous for attiéké', 'The city was the birthplace of Félix Houphouët-Boigny']),
  ('Zagreb', 'Croatia',
    ARRAY['Known for its colorful rooftops', 'Home to the Cathedral of Zagreb'],
    ARRAY['The cathedral is Croatia’s tallest building', 'Zagreb’s funicular is one of the shortest'],
    ARRAY['Famous for štrukli', 'The Museum of Broken Relationships is unique']);
-- CITY SEED DATA
INSERT INTO city (name) VALUES
  ('Tokyo'),
  ('Paris'),
  ('Berlin'),
  ('Moscow'),
  ('Beijing'),
  ('Seoul'),
  ('New York'),
  ('Los Angeles'),
  ('Cape Town'),
  ('Barcelona'),
  ('Rome'),
  ('Vienna'),
  ('Cairo'),
  ('Bangkok'),
  ('Amsterdam'),
  ('Toronto'),
  ('Vancouver');
